@baseUrl = http://localhost:30577/api/appointment-service
@admin_jwt = Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHNvbG1hci5jb20iLCJnaXZlbl9uYW1lIjoiQWRtaW4gQWRtaW4iLCJzdWIiOiI5N2Y1NDRhZC04MmFlLTRjMmEtYjRjMi0yNmNiZTU3ZGJlNTciLCJyb2xlIjoiQ2xpZW50ZSIsIm5iZiI6MTc2NTIzMTQ3MywiZXhwIjoxNzY1ODM2MjczLCJpYXQiOjE3NjUyMzE0NzMsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcwMDEiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MDAxIn0.oJxOR-pln6qg7bNGYvT0OGDY24sbZPdHUO9tARd5jqmjxOpGF3sCmVkzFXA_uUI-LOKkyyfrdGNzfqEBPTKslA

### Get All Restaurants
GET {{baseUrl}}/Appointment
Authorization: {{admin_jwt}}
Accept: application/json

### Get Appointment By Id
GET {{baseUrl}}/Appointment/1
Authorization: {{admin_jwt}}
Accept: application/json

### GET Appointments By Restaurant Id
GET {{baseUrl}}/Appointment/restaurant/1
Authorization: {{admin_jwt}}
Accept: application/json

### GET With Date Range
GET {{baseUrl}}/Appointment/restaurant/1?startDate=2025-12-08&endDate=2025-12-09
Authorization: {{admin_jwt}}
Accept: application/json

### Create New Appointment
POST {{baseUrl}}/Appointment
Authorization: {{admin_jwt}}
Content-Type: application/json
{
    "restaurantId": 1,
    "tableInventoryId": 1,
    "appointmentDate": "2025-12-11T10:00:00",
    "startTime": "2025-12-11T10:00:00",
    "endTime": "2025-12-11T11:30:00",
    "paxCount": 4,
    "notes": "Birthday celebration",
    "createdBy": "Ricardo Arevalo",
    "customers": [
      {
        "siteId": 1,
        "roomNumber": "101",
        "fullName": "Morty Smith",
        "email": "morty.smith@outlook.com"
      }
    ],
    "specialEvents": []
}

### Delete Appointment By Id
DELETE {{baseUrl}}/Appointment/2
Authorization: {{admin_jwt}}
Accept: application/json


