@baseUrl = http://localhost:30577
@gerente_jwt = Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRpdXJ2YW4xQGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJJdsOhbiBUYXBpYSIsInN1YiI6IjI3YzI3Y2U2LTJhNmItNGFjYS1hMjg0LTg2YTM2YjUxYjk1MiIsIkFzcE5ldC5JZGVudGl0eS5TZWN1cml0eVN0YW1wIjoiSlFHQjNNVFYySkFPRjVRSkxCTkRZSzRGNERMSVVJREEiLCJuYmYiOjE3Njg5MjIyNDgsImV4cCI6MTc2OTUyNzA0OCwiaWF0IjoxNzY4OTIyMjQ4LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MDAxIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzAwMSJ9.0hP2-7hP7DyGWl51PxrpomFZ6SasCtpSla4seLM4TVBtg4I0JmL2IBljtOqdkcbu7IJg1KUw5BOUl2wu5hECkw

###
# =====================================================
# Reportes Controller (/finanzas/api/reportes)
# Nota: Requiere un token JWT con roles específicos.
# =====================================================

# @name getVentasReport
# Obtiene el reporte de ventas.
# Roles permitidos: GerenteHotel, AdministradorSistema
GET {{baseUrl}}/api/finanzas/api/reportes/ventas
Authorization: {{gerente_jwt}}

###

# @name getOcupacionReport
# Obtiene el reporte de ocupación.
# Roles permitidos: GerenteHotel, AdministradorSistema, Recepcionista
GET {{baseUrl}}/api/finanzas/api/reportes/ocupacion
Authorization: {{gerente_jwt}}
