#@baseUrl = http://localhost:30577
@baseUrl = https://apiqa.solmar.com
@jwt = Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Iml2YW4udGFwaWFAc29sbWFyLmNvbSIsImdpdmVuX25hbWUiOiJJdsOhbiBUYXBpYSIsInN1YiI6IjI2NmEzMTNkLTJlOGMtNGM4Ny1iNDg5LTFmYWUzMTFjM2ZhMCIsIkFzcE5ldC5JZGVudGl0eS5TZWN1cml0eVN0YW1wIjoiNTNEWlZDSVlaV1VBTTZVQ0pOMlZEQkhLWDZYTERHNUEiLCJQZXJzb25JZCI6IjE4IiwicGhvbmVfbnVtYmVyIjoiKzUxOTU1NDc4NjY0Iiwicm9sZSI6IkNsaWVudGUiLCJuYmYiOjE3NzMwNTUxMzUsImV4cCI6MTc3MzY1OTkzNSwiaWF0IjoxNzczMDU1MTM1LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MDAxIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzAwMSJ9.aj4O-IEvQw8Vp_nfodPnNXWfeyj6dZESKZLVgROJcWvnkhFuInnD-SW_9wTY4Ell0kS0FsBi517Zzmz7ZHasug
###
# =====================================================
# Memberships (/memberships)
# =====================================================

## GetContractByContractNumber
GET {{baseUrl}}/api/memberships/76349
Accept: application/json

### GetContractByEmailContractNumber
GET {{baseUrl}}/api/memberships/verify/pavdaddy@neo.rr.com/76349
Accept: application/json

###
## GetContractByContractNumber
GET {{baseUrl}}/api/memberships/personexternalid/1371875/details
Accept: application/json

###
## GetCoMembersByPersonExternalId
GET {{baseUrl}}/api/memberships/comembers/1371875
Accept: application/json

###
# =====================================================
# Membership Features (/api/memberships/features)
# =====================================================

###
# Create a new Co-Member Invitation
POST {{baseUrl}}/api/memberships/features/comember-invitations
Content-Type: application/json
Authorization: {{jwt}}

{
  "contractId": "C-12345",
  "coMemberPersonId": 56138,
  "email": "diurvan1@gmail.com",
  "phoneNumber": "955478664",
  "fullName": "Nombre comember"
}

###
# Get a Co-Member Invitation
GET {{baseUrl}}/api/memberships/features/comember-invitations
Content-Type: application/json
Authorization: {{jwt}}


###
# Update a Co-Member Invitation's status
# This endpoint allows you to update the status of a co-member invitation. You can accept or reject the invitation by setting the "status" field accordingly.
# For example, to accept the invitation, set "status" to "ACCEPTED". To reject, set it to "REJECTED".
PUT {{baseUrl}}/api/memberships/features/comember-invitations/1
Content-Type: application/json
Authorization: {{jwt}}

{
  "status": "ACCEPTED"
}

###
# Create a new Guest
POST {{baseUrl}}/api/memberships/features/guests
Content-Type: application/json
Authorization: {{jwt}}

[
  {
    "contractId": "104581",
    "reservationNumber": "1344414",
    "fullName": "asdasdasd",
    "email": "asdasd@asdasd.com",
    "phoneNumber": "1212121212",
    "address": "asdasdasd",
    "relationship": "Parent",
    "useReservationInAbsence": true
  },
  {
    "contractId": "104581-2",
    "reservationNumber": "1344414-2",
    "fullName": "asdasdasd-2",
    "email": "asdasd@asdasd.com-2",
    "phoneNumber": "1212121212-2",
    "address": "asdasdasd-2",
    "relationship": "Parent-2",
    "useReservationInAbsence": false
  }
]

###
# Update a Guest
PUT {{baseUrl}}/api/memberships/features/guests/1
Content-Type: application/json

{
  "fullName": "John A. Doe",
  "status": "Inactive"
}

###
# Get a Guests Invitation
GET {{baseUrl}}/api/memberships/features/guests
Content-Type: application/json
Authorization: {{jwt}}


###
# Create a new Companion
POST {{baseUrl}}/api/memberships/features/companions
Content-Type: application/json
Authorization: {{jwt}}

[
  {
    "contractId": "C-12345",
    "reservationNumber": "R-12345",
    "givenName": "Jane",
    "surnName": "Smith",
    "email": "diurvan1@gmail.com",
    "phoneNumber": "555-555-5555"
  }
]

###
# Update a Companion
PUT {{baseUrl}}/api/memberships/features/companions/1
Content-Type: application/json
Authorization: {{jwt}}

{
  "email": "jane.smith.new@example.com"
}

###
# Get a Companion Invitation
GET {{baseUrl}}/api/memberships/features/companions
Content-Type: application/json
Authorization: {{jwt}}



###
# Send Vacation Exchange Notification
# vacationExchange: 0 for RCI, 1 for Interval, 3 for Thrid Home
POST {{baseUrl}}/api/memberships/features/vacation-exchange-notification
Content-Type: application/json
Authorization: {{jwt}}

{
  "vacationExchange": 0,
  "memberName": "John Doe",
  "memberEmail": "diurvan1@gmail.com",
  "memberContactNumber": "",
  "contractId": "C-12345",
  "membershipId": "M-12345",
  "exchangeType": "RCI",
  "usageYear": "2024",
  "accelerationYear": "2025",
  "unitType": "Villa",
  "unitNumber": "V-123",
  "weekNumber": 23
}


###
# Send Special Occasion Notification
# contactType: "Email", "Call" and "Lobby"
POST {{baseUrl}}/api/memberships/features/special-occasions-notification
Content-Type: application/json
Authorization: {{jwt}}

{
  "consumptionCenterGroupId": "1",
  "contactType": "Email",
  "ContactDate": "01/01/2024",
  "ContactTime": "07:00AM"
}


###
# Send Membership Request Notification
# contactType: "Email", "Phone"
POST {{baseUrl}}/api/memberships/features/membership-request-notification
Content-Type: application/json
Authorization: {{jwt}}

{
  "contactType": "Email",
  "memberEmail": "pepe@pepe.com",
  "memberPhoneNumber": "9999999"
}

###
# Send Group Request Notification
# contactType: "Email", "Call" and "Lobby"
POST {{baseUrl}}/api/memberships/features/group-request-notification
Content-Type: application/json
Authorization: {{jwt}}

{
  "consumptionCenterGroupId": "1",
  "restaurant": "Restaurante",
  "quantity": "10"
}
