#@baseUrl = http://localhost:30577
@baseUrl = https://apiqa.solmar.com
@jwt = Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Iml2YW4udGFwaWFAc29sbWFyLmNvbSIsImdpdmVuX25hbWUiOiJJdsOhbiBUYXBpYSIsInN1YiI6IjI2NmEzMTNkLTJlOGMtNGM4Ny1iNDg5LTFmYWUzMTFjM2ZhMCIsIkFzcE5ldC5JZGVudGl0eS5TZWN1cml0eVN0YW1wIjoiNTNEWlZDSVlaV1VBTTZVQ0pOMlZEQkhLWDZYTERHNUEiLCJQZXJzb25JZCI6IjE4Iiwicm9sZSI6IkNsaWVudGUiLCJuYmYiOjE3NzIwMjY4OTksImV4cCI6MTc3MjYzMTY5OSwiaWF0IjoxNzcyMDI2ODk5LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MDAxIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzAwMSJ9.F5os7dMXoDL14VA36tgMvb_yn_5_ztVdP-k5gqPLLZu0nHcTeeBPYF4ETZgeyGaEppbmDksstpE5ZKIw7omQGw
###
# =====================================================
# Memberships (/memberships)
# =====================================================

## GetContractByContractNumber
GET {{baseUrl}}/api/memberships/76349
Accept: application/json

### GetContractByEmailContractNumber
GET {{baseUrl}}/api/memberships/verify/pavdaddy@neo.rr.com/76349
Accept: application/json

###
## GetContractByContractNumber
GET {{baseUrl}}/api/memberships/personexternalid/1371875/details
Accept: application/json

###
## GetCoMembersByPersonExternalId
GET {{baseUrl}}/api/memberships/comembers/1371875
Accept: application/json

###
# =====================================================
# Membership Features (/api/memberships/features)
# =====================================================

###
# Create a new Co-Member Invitation
POST {{baseUrl}}/api/memberships/features/comember-invitations
Content-Type: application/json
Authorization: {{jwt}}

{
  "contractId": "C-12345",
  "coMemberPersonId": 1371876,
  "email": "comember@example.com",
  "phoneNumber": "555-123-4567"
}

###
# Get a Co-Member Invitation
GET {{baseUrl}}/api/memberships/features/comember-invitations
Content-Type: application/json
Authorization: {{jwt}}


###
# Update a Co-Member Invitation's status
PUT {{baseUrl}}/api/memberships/features/comember-invitations/1
Content-Type: application/json
Authorization: {{jwt}}

{
  "status": "Accepted"
}

###
# Create a new Guest
POST {{baseUrl}}/api/memberships/features/guests
Content-Type: application/json
Authorization: {{jwt}}
{
  "contractId": "C-12345",
  "personId": 1371875,
  "fullName": "John Doe",
  "email": "johndoe@example.com",
  "phoneNumber": "555-987-6543",
  "address": "123 Main St, Anytown, USA",
  "relationship": "Friend",
  "useReservationInAbsence": true
}

###
# Update a Guest
PUT {{baseUrl}}/api/memberships/features/guests/1
Content-Type: application/json

{
  "fullName": "John A. Doe",
  "status": "Inactive"
}

###
# Get a Guests Invitation
GET {{baseUrl}}/api/memberships/features/guests
Content-Type: application/json
Authorization: {{jwt}}


###
# Create a new Companion
POST {{baseUrl}}/api/memberships/features/companions
Content-Type: application/json
Authorization: {{jwt}}

{
  "contractId": "C-12345",
  "personId": 1371875,
  "fullName": "Jane Smith",
  "email": "janesmith@example.com",
  "phoneNumber": "555-555-5555"
}

###
# Update a Companion
PUT {{baseUrl}}/api/memberships/features/companions/1
Content-Type: application/json
Authorization: {{jwt}}

{
  "email": "jane.smith.new@example.com"
}

###
# Get a Companion Invitation
GET {{baseUrl}}/api/memberships/features/companions
Content-Type: application/json
Authorization: {{jwt}}


###
# Send a Vacation Exchange Notification
POST {{baseUrl}}/api/memberships/features/vacation-exchange-notification
Content-Type: application/json

{
  "contractId": "C-12345",
  "personId": 1371875,
  "intervalMembershipId": "INT-98765",
  "exchangeType": "Intercambio de crucero",
  "depositYear": "2025",
  "accelerationYear": "2026",
  "unitType": "Suite de 1 recámara",
  "unitNumber": "A-201",
  "weekNumber": 32
}