###@baseUrl = https://apiqa.solmar.com
@baseUrl = http://localhost:30577
@admin_jwt = Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHNvbG1hci5jb20iLCJnaXZlbl9uYW1lIjoiICIsInN1YiI6IjM2ZmQwMDdiLTFkNGUtNDFlNS1iMDgyLWE5YzdjZjQ2MzE4OCIsIkFzcE5ldC5JZGVudGl0eS5TZWN1cml0eVN0YW1wIjoiWjUzTDVZTlBEVk4yT1VYNUxGM1JQVjRLR1dETTQ1NVkiLCJyb2xlIjoiQWRtaW5pc3RyYWRvclNpc3RlbWEiLCJwZXJtaXNzaW9uIjpbInJlc2VydmFzOmxlZXIiLCJyZXNlcnZhczpjcmVhciIsInJlc2VydmFzOmNhbmNlbGFyIiwiZmluYW56YXM6dmVyX3JlcG9ydGVzIiwiYWRtaW46Z2VzdGlvbmFyX3VzdWFyaW9zIiwiYWRtaW46Z2VzdGlvbmFyX3JvbGVzIl0sIm5iZiI6MTc3MDIwNzE1OSwiZXhwIjoxNzcwODExOTU5LCJpYXQiOjE3NzAyMDcxNTksImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcwMDEiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MDAxIn0.n0VGp5OROt1smwkOk6uvcrk443KadpSqvH1BQUCR4QnzCAFZwddPbQ2cbtZDsymVtqx_VPsodjVq1610PnQy8w
###
# =====================================================
# Reservations (/api/reservations)
# =====================================================

### Get Reservation Detail By Id
GET {{baseUrl}}/api/reservations/reservation/3
Authorization: {{admin_jwt}}
Accept: application/json

### Get Reservation By Reservation Number
GET {{baseUrl}}/api/reservations/reservation/lookup/RSV-3Z23NE
Authorization: {{admin_jwt}}
Accept: application/json

### Change Reservation Status
POST {{baseUrl}}/api/reservations/reservation/change-status
Authorization: {{admin_jwt}}
Content-Type: application/json
{
  "reservationId": 2,
  "reservationNumber": "RSV-SX5QLQ",
  "reservationStatus": "Confirmed",
  "personsToConfirm" : 1
}

### Update Reservation
PUT {{baseUrl}}/api/reservations/reservation/12
Authorization: {{admin_jwt}}
Content-Type: application/json
Accept: application/json

{
  "reservationId": 12,
  "details": {
    "serviceDate": "2026-01-03",
    "availabilityId": 5,
    "capacity": 6,
    "notes": "Cambiar a mesa interior, por favor",
    "cleaningTime": "00:15:00"
  }
}

### Update Reservation Details (PATCH)
PATCH {{baseUrl}}/api/reservations/reservation/6/details
Authorization: {{admin_jwt}}
Content-Type: application/json
Accept: application/json

{
  "serviceDate": "2026-01-04",
  "startTime": "18:30",
  "endTime": "20:00",
  "capacity": 3,
  "employeeCode": "EMP123",
  "notes": "Actualización de fecha y hora, 3 personas.",
  "reservationDetailPersons": [
      {
        "name": "Juan Perez",
        "age": 39,
        "personType": "Adulto",
        "personNumber": 2,
        "personStatus": "Confirmado"
      },
      {
        "name": "Ana Perez",
        "age": 12,
        "personType": "Niño",
        "personNumber": 2,
        "personStatus": "Confirmado"
      }
    ]
}


### Get Hotel Reservation By ReservationNumber
GET {{baseUrl}}/api/reservations/reservation/hotel/1280474
### Get Hotel Reservation By Email and ReservationNumber diurvan1@gmail.com
GET {{baseUrl}}/reservations/reservation/verify/diurvan1@gmail.com/1280474
Authorization: {{admin_jwt}}
Accept: application/json


### Get Reservations By Consumption Center And DateRange
POST {{baseUrl}}/api/reservations/reservation/consumptioncenter/search
Authorization: {{admin_jwt}}
Content-Type: application/json
{
  "consumptionCenterId": 3,
  "startDate": "2026-01-22",
  "endDate": "2026-01-23"
}

### Get My Reservations By DateRange
GET {{baseUrl}}/api/reservations/reservation/search/me?startDate=2025-12-01&endDate=2026-12-31
Authorization: {{admin_jwt}}
Accept: application/json

### Create Reservation
POST {{baseUrl}}/api/reservations/reservation
Authorization: {{admin_jwt}}
Content-Type: application/json
Accept: application/json

{
  "consumptionCenterId": 3,
  "details": {
    "serviceDate": "2026-01-02",
    "startTime": "15:00",
    "endTime": "16:00",
    "capacity": 4,
    "notes": "Mesa en la terraza, por favor.",
    "createdBy": "Rick",
    "availabilityId": 3,
    "employeeCode": "EMP123",
    "reservationDetailPersons": [
      {
        "name": "Juan Perez",
        "age": 39,
        "personType": "Adulto",
        "personNumber": 2,
        "personStatus": "Confirmado"
      },
      {
        "name": "Ana Perez",
        "age": 12,
        "personType": "Niño",
        "personNumber": 2,
        "personStatus": "Confirmado"
      }
    ]
  }
}

### Search Availability
POST {{baseUrl}}/api/reservations/reservation/availability
Content-Type: application/json
Accept: application/json

{
  "consumptionCenterId": 3,
  "capacity": 4,
  "reservationDate": "2026-01-02"
}

###
# =====================================================
# Indicadores (/reservations/indicadores)
# =====================================================

# @name getAllIndicadores
# Obtiene todos los indicadores de todos los hoteles.
GET {{baseUrl}}/api/reservations/reservation/indicadores/2025

###

# @name getAllIndicadoresPeriod
# Obtiene los indicadores para un hotel y mes específicos.
GET {{baseUrl}}/api/reservations/reservation/indicators/HGSLE/01/2025

###

# @name getIndicadores
# Obtiene los indicadores para un hotel específico.
GET {{baseUrl}}/reservations/reservation/indicadores/H1


###
# =====================================================
# Attributes
# =====================================================

### Get All Offer Attributes
GET {{baseUrl}}/api/reservations/attributes/offers


### Get All Offer Attributes grouped by Type
GET {{baseUrl}}/api/reservations/attributes/offers/grouped

###
# =====================================================
# Consumption Center
# =====================================================

### Get All Consumption Centers
#GET {{baseUrl}}/api/reservations/reservation/consumptioncenter

### Get Consumption Center Detail By Id
#GET {{baseUrl}}/api/reservations/reservation/consumptioncenter/detail/15

### Get Offer By Consumption Center Id
GET {{baseUrl}}/api/reservations/consumptioncenter/15/offers?attributeIds=20
Accept-Language: en-US


### Get Consumption Centers Types
GET {{baseUrl}}/api/reservations/consumptioncenter/types
Authorization: {{admin_jwt}}

### Get Consumption Centers Groups
GET {{baseUrl}}/api/reservations/consumptioncenter/groups
Authorization: {{admin_jwt}}

### Get Consumption Center By Group External Id
GET {{baseUrl}}/api/reservations/consumptioncenter/group/6
Accept: application/json

### Get Consumption Center By Type Id
GET {{baseUrl}}/api/reservations/consumptioncenter/type/1
Accept: application/json

### Get Consumption Center Inventories
GET {{baseUrl}}/api/reservations/consumptioncenter/2/inventories
Authorization: {{admin_jwt}}
Accept: application/json

### Get Consumption Center By Hotel Group And Type
### GroupId and TypeId
GET {{baseUrl}}/api/reservations/consumptioncenter/grouptype/1
Authorization: {{admin_jwt}}
Accept-Language: en-US
Accept: application/json


### Get Consumption Center By Hotel Group
### GroupId
GET {{baseUrl}}/api/reservations/consumptioncenter/bygroup/1
Authorization: {{admin_jwt}}
Accept-Language: en-US
Accept: application/json

### Get Consumption Center By Hotel Type
### TypeId
GET {{baseUrl}}/api/reservations/consumptioncenter/bytype/2
Authorization: {{admin_jwt}}
Accept-Language: en-US
Accept: application/json




### Get Consumption Center Attributes
GET {{baseUrl}}/api/reservations/consumptioncenter/15/attributes
Authorization: {{admin_jwt}}
Accept-Language: en-US
Accept: application/json

### Add Attributes to Consumption Center
POST {{baseUrl}}/api/reservations/consumptioncenter/15/attributes
Authorization: {{admin_jwt}}
Content-Type: application/json
[
  {
    "attributeId": 1,
    "isKeyAttribute": true
  },
  {
    "attributeId": 2,
    "isKeyAttribute": false
  }
]

### Remove Attribute from Consumption Center
DELETE {{baseUrl}}/api/reservations/consumptioncenter/1/attributes/1
Authorization: {{admin_jwt}}
Accept: application/json

### Get CC By Group And Type
# POST {{baseUrl}}/reservations/reservation/consumptioncenter/search/group/type
# Content-Type: application/json
# {
#   "groupId": 6,
#   "typeId": 2
# }

### Create Consumption Center Type
POST {{baseUrl}}/api/reservations/consumptioncenter/types
Content-Type: application/json
{
  "name": "Restaurant",
  "description": "Operational unit dedicated to offering curated restaurants, scheduled within defined dates, times, and capacity."
}

### Create Consumption Center
POST {{baseUrl}}/api/reservations/consumptioncenter
Authorization: {{admin_jwt}}
Content-Type: application/json
{
    "name": "Bacari",
    "capacity": "800",
    "email": "ivan.tapia@inteec.la",
    "phoneNumber": "6241234567",
    "startTime": "12:00",
    "endTime": "22:00",
    "startDate": "2026-01-21",
    "endDate": "2027-01-21",
    "weekDays": "Mon,Tue,Wed,Thu,Fri",
    "description": "Restaurant Description",
    "latitude": 22.87869,
    "longitude": -109.91299,
    "consumptionCenterGroupId": 6,
    "consumptionCenterTypeId": 2,
    "attribute": {
        "name": "Cuisine",
        "tags": [
            "Italian",
            "Seafood",
            "Pasta"
        ]
    }
}

### Create Consumption Center Group
POST {{baseUrl}}/api/reservations/consumptioncenter/groups
Content-Type: application/json
{
  "externalId": 1,
  "externalName": "Solmar Beach Club"
}

### Create Consumption Center Offer
POST {{baseUrl}}/api/reservations/consumptioncenter/offer
Authorization: {{admin_jwt}}
Content-Type: application/json

{
  "name": "Sample Offer Name",
  "description": "This is a sample offer description.",
  "isActive": true,
  "startTime": "10:00:00",
  "endTime": "22:00:00",
  "startDate": "2026-01-28T00:00:00",
  "endDate": "2026-12-31T00:00:00",
  "weekDays": "Lunes,Martes,Miércoles,Jueves,Viernes",
  "consumptionCenterId": 3,
  "offerItems": [
    {
      "name": "Offer Item 1",
      "description": "Description for offer item 1",
      "price": 100.50,
      "cost": 50.25,
      "specialInformation": "Special info for item 1"
    }
  ]
}

###
# =====================================================
# Inventories
# =====================================================

### Get Inventory Types
GET {{baseUrl}}/api/reservations/inventory/types
Authorization: {{admin_jwt}}
Accept: application/json

### Create Inventory Type
POST {{baseUrl}}/api/reservations/inventory/type
Authorization: {{admin_jwt}}
Content-Type: application/json
{
  "name": "Table",
  "description": "Table available for seating and reservations."
}

### Get Inventory Attributes
GET {{baseUrl}}/api/reservations/inventory/attributes
Authorization: {{admin_jwt}}
Accept: application/json

### Create Inventory Attributes
POST {{baseUrl}}/api/reservations/inventory/attribute
Authorization: {{admin_jwt}}
Content-Type: application/json
{
  "name": "Mesa Interior",
  "description": "Mesa en area interior del restaurante",
  "capacity": 6,
  "specialInformation": "Cerca de la ventana",
  "attribute": {
    "name": "Interior",
    "tags": ["Interior","Window"],
    "attributeType": {
      "name": "Location"
    }
  }
}

### Create Consumption Center Inventory
POST {{baseUrl}}/api/reservations/consumptioncenter/inventory
Authorization: {{admin_jwt}}
Content-Type: application/json
{
  "name": "A-E4",
  "minCapacity": 2,
  "maxCapacity": 8,
  "startTime": "7:00",
  "endTime": "22:00",
  "price": 50,
  "inventoryTypeId": 1,
  "consumptionCenterId": 3
}

###
# =====================================================
# Offers
# =====================================================

### Get Offer By Id
GET {{baseUrl}}/api/reservations/consumptioncenter/3/offers
Authorization: {{admin_jwt}}
Accept: application/json

### Get Offers By Date Range
POST {{baseUrl}}/reservations/consumptioncenter/offers
Authorization: {{admin_jwt}}
Content-Type: application/json

{
  "startDate": "2025-12-01",
  "endDate": "2025-12-31"
}

### Get Offers By Consumption Center Id
GET {{baseUrl}}/reservations/consumptioncenter/offers/1

### Create Consumption Center Offer
POST {{baseUrl}}/reservations/consumptioncenter/offer
Authorization: {{admin_jwt}}
Content-Type: application/json

{
  "consumptionCenterId": 1,
  "name": "Happy Hour",
  "description": "2x1 Drinks",
  "isActive": true,
  "startTime": "16:00",
  "endTime": "18:00",
  "startDate": "2025-01-01",
  "endDate": "2025-12-31",
  "weekDays": "Mon,Tue,Wed,Thu,Fri"
}

### Create Consumption Center OfferItem
POST {{baseUrl}}/api/reservations/consumptioncenter/offer/items
Authorization: {{admin_jwt}}
Content-Type: application/json

{
  "offerId": 1,
  "offerItems": [
    {
      "name": "Other Margarita",
      "description": "Other Type Of Margarita",
      "price": 150.00,
      "specialInformation": "Salt rim",
      "medias": [
        {
          "url": "https://cdn.solmar.com/margarita.jpg",
          "type": 0
        }
      ],
      "items": [
        {
          "name": "Tequila Blanco",
          "description": "100% agave tequila",
          "quantity": 50,
          "unitOfMeasure": "ml",
          "specifications": "Premium brand"
        },
        {
          "name": "Lime Juice",
          "description": "Fresh squeezed lime juice",
          "quantity": 30,
          "unitOfMeasure": "ml",
          "specifications": "Daily fresh"
        },
        {
          "name": "Triple Sec",
          "description": "Orange liqueur",
          "quantity": 20,
          "unitOfMeasure": "ml",
          "specifications": "Cointreau"
        }
      ]
    }
  ]
}
###
# =====================================================
# Inventory Types
GET {{baseUrl}}/api/reservations/inventory/types
Authorization: {{admin_jwt}}
Accept: application/json

###
# =====================================================
# Consumption Centers
# =====================================================
GET {{baseUrl}}/api/reservations/consumptioncenter/
Authorization: {{admin_jwt}}
Accept: application/json


###
# =====================================================
# Reservation Media (/api/reservationdetails/{id}/reservationmedia)
# =====================================================

### Upload Reservation Media
curl -X POST "http://localhost:30577/api/reservations/reservationmedia/1" -F "File=@C:\Users\diurv\Downloads\Logo1.jpg" -F "MediaType=Image" -F "Description=Logo de la empresa" -w "\nHTTP Status: %{http_code}\n"

curl -X POST "http://localhost:30577/api/media/upload" -F "File=@C:\Users\diurv\Downloads\Logo1.jpg" -F "MediaType=Image" -F "resourceCatalog=ConsumptionCenter" -F "resourceCatalogId=1" -F "Description=Logo de la empresa" -w "\nHTTP Status: %{http_code}\n"
