# k8s/overlays/qa/image-tags.yaml
# En un escenario real, aquí podrías usar tags específicos para QA,
# ej: diurvan/solmar-backend:yarp-proxy-qa-v1.2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarp-proxy
spec:
  template:
    spec:
      containers:
      - name: yarp-proxy
        image: diurvan/solmar-backend-yarpproxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  template:
    spec:
      containers:
      - name: auth-service
        image: diurvan/solmar-backend-authservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservations-service
spec:
  template:
    spec:
      containers:
      - name: reservations-service
        image: diurvan/solmar-backend-reservationsservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finanzas-service
spec:
  template:
    spec:
      containers:
      - name: finanzas-service
        image: diurvan/solmar-backend-finanzasservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
spec:
  template:
    spec:
      containers:
      - name: notifications-service
        image: diurvan/solmar-backend-notificationsservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  template:
    spec:
      containers:
      - name: catalog-service
        image: diurvan/solmar-backend-catalogservice
