# k8s/overlays/prod/common-env-patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservations-service
spec:
  template:
    spec:
      containers:
      - name: reservations-service
        envFrom:
        - configMapRef:
            name: solmar-config-prod
        - secretRef:
            name: solmar-secrets-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memberships-service
spec:
  template:
    spec:
      containers:
      - name: memberships-service
        envFrom:
        - configMapRef:
            name: solmar-config-prod
        - secretRef:
            name: solmar-secrets-prod
