# k8s/overlays/prod/image-tags.yaml
# En producción, SIEMPRE usar tags específicos y versionados, NUNCA 'latest'.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarp-proxy
spec:
  template:
    spec:
      containers:
      - name: yarp-proxy
        image: diurvan/solmar-backend:yarp-proxy-v1.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  template:
    spec:
      containers:
      - name: auth-service
        image: diurvan/solmar-backend:auth-service-v1.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservations-service
spec:
  template:
    spec:
      containers:
      - name: reservations-service
        image: diurvan/solmar-backend:reservations-service-v1.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finanzas-service
spec:
  template:
    spec:
      containers:
      - name: finanzas-service
        image: diurvan/solmar-backend:finanzas-service-v1.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
spec:
  template:
    spec:
      containers:
      - name: notifications-service
        image: diurvan/solmar-backend:notifications-service-v1.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  template:
    spec:
      containers:
      - name: catalog-service
        image: diurvan/solmar-backend:catalog-service-v1.0.0
