# k8s/overlays/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- files:
  - prod-config.properties
  name: solmar-config-prod

# Genera el Secret leyendo el archivo .env (Kustomize lo codifica por ti)
secretGenerator:
- envs:
  - prod-secrets.env
  name: solmar-secrets-prod

# Aplica los patches de imagen y réplicas
patchesStrategicMerge:
- replicas.yaml
- common-env-patch.yaml

# Aplica el parche de variables de entorno a TODOS los Deployments
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/envFrom
      value:
        - configMapRef:
            name: solmar-config-prod
        - secretRef:
            name: solmar-secrets-prod
  target:
    kind: Deployment
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: Jwt__ExpirationInMinutes
        value: "15"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: Jwt__RefreshTokenExpirationInMinutes
        value: "10080"
  target:
    kind: Deployment
    name: auth-service
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: ReservationRules__CapacityBypass__AllowedRoles__0
        value: "ADMIN"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: ReservationRules__CapacityBypass__AllowedRoles__1
        value: "GERENTE"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: ReservationRules__CapacityBypass__AllowedRoles__2
        value: "CONCIERGE"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: ReservationRules__CapacityBypass__AllowedApiKeys__0
        value: "sol_prod_admin_dashboard_2026"
  target:
    kind: Deployment
    name: reservations-service
resources:
- ../../base
images:
- name: diurvan/solmar-backend-authservice
  newName: diurvan/solmar-backend-authservice
  newTag: bd02e33
- name: diurvan/solmar-backend-catalogservice
  newName: diurvan/solmar-backend-catalogservice
  newTag: bd02e33
- name: diurvan/solmar-backend-finanzasservice
  newName: diurvan/solmar-backend-finanzasservice
  newTag: bd02e33
- name: diurvan/solmar-backend-localizationservice
  newName: diurvan/solmar-backend-localizationservice
  newTag: bd02e33
- name: diurvan/solmar-backend-mediaservice
  newName: diurvan/solmar-backend-mediaservice
  newTag: bd02e33
- name: diurvan/solmar-backend-membershipsservice
  newName: diurvan/solmar-backend-membershipsservice
  newTag: bd02e33
- name: diurvan/solmar-backend-notificationsservice
  newName: diurvan/solmar-backend-notificationsservice
  newTag: bd02e33
- name: diurvan/solmar-backend-reservationsservice
  newName: diurvan/solmar-backend-reservationsservice
  newTag: bd02e33
- name: diurvan/solmar-backend-yarpproxy
  newName: diurvan/solmar-backend-yarpproxy
  newTag: bd02e33
